pub mod agent;
pub mod approval;
pub mod attachments;
pub mod background_process;
mod bash_arity;
pub mod bench;
pub mod cache;
pub mod chat;
pub mod cli;
pub mod commands;
mod compaction;
pub mod config;
pub mod context;
pub mod control;
pub mod events;
pub mod executor;
pub mod file_tools;
mod frontmatter;
pub mod git;
pub mod harness;
pub mod hooks;
pub mod input_queue;
pub mod instructions;
pub mod interaction;
pub mod lsp;
mod markdown_render;
pub mod mcp;
pub mod model;
pub mod patch;
mod process_tree;
pub mod prompt_context;
pub mod protocol;
pub mod review;
pub mod session;
pub mod setup;
pub mod skills;
pub mod subagent;
pub mod tool_registry;
pub mod tui;
pub mod ui;
mod viewport;
